# Generated by Django 3.1.4 on 2021-03-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
